name: Deploy frededison.net
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Release to server
        env:
          H: ${{ secrets.SSH_HOST }}
          U: ${{ secrets.SSH_USER }}
        run: |
          set -eux
          TS=$(date -u +%Y%m%d%H%M%S)
          DEST="/srv/fred/www/frededison.net/public/releases/$TS"
          ssh -o StrictHostKeyChecking=no "$U@$H" "mkdir -p '$DEST'"
          rsync -az --delete \
            --exclude '.git' --exclude '.github' \
            ./ "$U@$H:$DEST/"
          ssh -o StrictHostKeyChecking=no "$U@$H" "\
            ln -sfn '$DEST' /srv/fred/www/frededison.net/public/current && \
            find /srv/fred/www/frededison.net/public/releases -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' | sort -nr | tail -n +6 | cut -d' ' -f2- | xargs -r rm -rf && \
            echo OK"
